REFERENCES = [
('atom','OpenStax · Atomic Structure and Symbolism','https://openstax.org/books/chemistry-2e/pages/2-3-atomic-structure-and-symbolism','원자핵·전자·원소·이온의 구분. 그림과 예제는 새로 작성.'),
('carriers','MIT OCW · Semiconductor Physics I','https://ocw.mit.edu/courses/6-012-microelectronic-devices-and-circuits-fall-2005/e1a94598c1fd641fc15636a9ad14de1a_lec2.pdf','결합, 캐리어, 도너·억셉터와 고정 전하.'),
('neutrality','MIT 6.012 · Charge Neutrality','https://web.mit.edu/course/6/6.012/FALL00/www/handouts/lec2.pdf','균일한 평형에서 캐리어 농도와 전하 중성 조건.'),
('junction','MIT OCW · PN Junction and MOS Electrostatics','https://ocw.mit.edu/courses/6-012-microelectronic-devices-and-circuits-fall-2005/9c9310d77a66dcf1e3a078a1fd2a3e8b_lecture5annotat.pdf','pn 접합의 확산·드리프트 균형과 공핍 근사.'),
('mos','MIT OCW · MOS Caps II; MOSFETs I','https://ocw.mit.edu/courses/6-012-microelectronic-devices-and-circuits-fall-2009/resources/mit6_012f09_lec10/','게이트에 의한 반전과 MOSFET의 구조·모형.'),
('ev','OpenStax · Electric Potential and Potential Difference','https://openstax.org/books/university-physics-volume-2/pages/7-2-electric-potential-and-potential-difference','전위차·전하·에너지와 eV의 정의.'),
('hv','TU Wien · Device Design Techniques','https://www.iue.tuwien.ac.at/phd/triebl/node9.html','평면 CMOS 확장, 측면 HV 드리프트와 전기장·온저항의 관계. 특정 레시피의 근거로 사용하지 않음.'),
('ldmos','TU Wien · Lateral DMOSFETs','https://www.iue.tuwien.ac.at/phd/park/node18.html','바디·드리프트·소스/드레인·바디 접촉, 측면 확산과 전기장 집중. PMOS 화면은 극성 대응 교육 예제.'),
('cmos-process','MIT OCW · Physics of Microfabrication, Lecture 22','https://ocw.mit.edu/courses/6-774-physics-of-microfabrication-front-end-processing-fall-2004/1skaz4sLHu2wMpolDYN0fBJfxfiRcPlGo_transcript.pdf','CMOS 공정 통합에서 게이트·주입·스페이서와 열 공정의 역할. 화면 순서는 자체 단순화.'),
('diffusion','TU Wien · Intrinsic Dopant Diffusion','https://www.iue.tuwien.ac.at/phd/puchner/node28.html','Fick 법칙, 결함을 통한 도펀트 이동과 단순 확산 모형의 한계.'),
('transport','MIT OCW · Semiconductor Physics II','https://ocw.mit.edu/courses/6-012-microelectronic-devices-and-circuits-spring-2009/4692cf463514c4f47d8629fab7d41c15_MIT6_012S09_lec03.pdf','캐리어 이동도·전도도·농도 의존성. 면저항의 상대 비교는 본 교재에서 가정을 두고 유도.'),
]

GLOSSARY = [
('원자 / Atom','양성자 수로 원소가 정해지는 물질의 구성 단위.','atoms'),
('이온 / Ion','전자를 잃거나 얻어 순전하를 띤 원자·분자.','atoms'),
('전자 / Electron','음전하를 가진 입자. 전도 전자와 결합 전자를 구분해 설명한다.','silicon'),
('정공 / Hole','가전자대의 빈 전자 상태를 양전하 캐리어로 기술한 것. 원자 빈자리와 다르다.','silicon'),
('캐리어 / Carrier','전하 수송을 기술하는 전자와 정공.','silicon'),
('밴드갭 / Band gap','가전자대와 전도대 사이의 허용 상태가 없는 에너지 간격.','silicon'),
('도핑 / Doping','반도체의 캐리어 특성을 조절하려고 원자를 도입하는 일.','doping'),
('도너 / Donor','전자를 제공할 수 있는 도펀트. Si에서 P·As 등이 사용된다.','doping'),
('억셉터 / Acceptor','전자를 받아들여 정공에 기여할 수 있는 도펀트. Si에서 B 등이 사용된다.','doping'),
('보상 / Compensation','도너와 억셉터의 효과가 일부 상쇄되는 것.','doping'),
('공핍층 / Depletion region','이동 캐리어가 줄어 고정 도펀트 전하가 드러나는 영역.','transistor'),
('반전 / Inversion','표면의 다수 캐리어 종류가 벌크와 반대로 바뀌는 상태.','transistor'),
('문턱전압 / Threshold voltage','강한 반전의 경계를 기술하는 소자 파라미터.','transistor'),
('전하수 / Charge state','이온 전하 q=ze에서 e의 배수 z.','beamline'),
('에너지 / Energy','입자 하나의 운동에너지. 전압·도즈와 단위가 다르다.','beamline'),
('도즈 / Dose','단위 면적에 입사한 이온 수. ions/cm².','dose'),
('농도 / Concentration','부피당 원자 또는 캐리어 수. 무엇을 셌는지 명시한다.','profile'),
('투영 비정 / Projected range','입사 방향 또는 기준 깊이 방향으로 투영한 평균 이동 범위.','profile'),
('스트래글 / Straggle','주입 깊이나 옆 방향 위치 분포의 퍼짐.','profile'),
('마스크 / Mask','주입·가공할 위치를 선택하기 위한 가림 구조.','channel'),
('틸트 / Tilt','빔과 웨이퍼 법선 사이의 각도.','channel'),
('트위스트 / Twist','표면 안에서 기준 결정 방향에 대한 회전각.','channel'),
('채널링 / Channeling','결정의 특정 방향에서 일부 이온이 깊게 진행하는 현상. 트랜지스터 채널과 다르다.','channel'),
('섀도잉 / Shadowing','기울어진 빔이 높은 구조물 때문에 가려지는 기하학적 효과.','channel'),
('균일도 / Uniformity','위치별 값의 차이를 기술하는 특성. 측정·계산 정의가 필요하다.','scan'),
('빈자리 / Vacancy','정상 격자 자리에 원자가 없는 결함. 정공과 구분한다.','anneal'),
('격자간 원자 / Interstitial','정상 격자 자리 사이에 있는 원자.','anneal'),
('활성화 / Activation','도펀트가 전기적으로 기여할 수 있는 상태가 되는 과정.','anneal'),
('열 이력 / Thermal budget','여러 열 공정이 확산·활성화 등에 미친 누적 영향. 온도×시간으로 일반화하지 않는다.','anneal'),
('웰·바디 / Well·Body','트랜지스터 채널의 바탕을 이루는 도핑 영역.','devices'),
('확장 / Extension','게이트 가까이 연결되는 얕은 소스·드레인 도핑 영역.','devices'),
('스페이서 / Spacer','게이트 옆벽 등에 만든 절연막 구조. 주입 위치 기준으로 사용할 수 있다.','devices'),
('드리프트 영역 / Drift region','HV 소자에서 전압 분산과 전류 경로를 함께 담당하는 도핑 영역.','devices'),
('바디 접촉 / Body contact','바디 전위를 정하기 위한 전기적 접촉 영역.','devices'),
('RESURF','층의 전하·두께·주변 구조를 설계해 표면 전기장을 완화하는 방법.','devices'),
('확산 / Diffusion','입자의 이동으로 농도 분포가 재배치되는 현상.','physics'),
('이동도 / Mobility','전기장에 대한 캐리어 이동의 용이함을 기술하는 값.','physics'),
('면저항 / Sheet resistance','얇은 도전층의 저항을 길이/폭 비율과 연결하는 값. Ω/□.','physics'),
('SIMS','이차 이온 질량분석. 원소 농도와 깊이 분포를 분석한다.','physics'),
('TED','과잉 결함 등으로 인해 일시적으로 빨라지는 도펀트 확산.','physics'),
]
