"""Assemble a self-contained static textbook from the original manuscript."""
from pathlib import Path
import sys,json,re,html
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'content'))
from textbook import CHAPTERS
from labs import LABS
from reference_data import REFERENCES,GLOSSARY
legacy=json.loads((ROOT/'content/legacy-labs.json').read_text('utf-8'))
def li(items):return ''.join('<li>'+s+'</li>' for s in items)
SHORT=['원자와 전하','실리콘·전자·정공','도핑과 캐리어','접합과 트랜지스터','이온주입 장비','도즈와 전류','에너지·깊이 분포','마스크·채널링','스캔과 균일도','손상과 어닐링','LV/HV 소자 공정','확산·활성화·측정']
def navlink(c,i):return f'<a href="#{c["id"]}"><span>{i:02}</span>{i}장 · {SHORT[i-1]}<small>{c["level"]}</small></a>'
def links(i):
    prev=CHAPTERS[i-1] if i else dict(id='intro',title='학습 지도')
    nxt=CHAPTERS[i+1] if i<11 else dict(id='review',title='용어집과 종합 복습')
    return f'<div class="chapter-pagination"><a href="#{prev["id"]}"><small>← 이전</small>{prev["title"]}</a><a href="#{nxt["id"]}"><small>다음 →</small>{nxt["title"]}</a></div>'
def quizzes(c):
    out=f'<section class="chapter-check" id="{c["id"]}-check" aria-labelledby="{c["id"]}-check-title"><div class="check-heading"><h3 id="{c["id"]}-check-title">확인하고 설명하기</h3><button type="button" data-reset-check="{c["id"]}" class="text-button">다시 풀기</button></div>'
    for j,(question,options,answer,reason) in enumerate(c['quiz']):
        qid=f'{c["id"]}-q{j+1}'
        out+=f'<article class="quiz-card chapter-question" data-answer="{answer}"><h4 id="{qid}"><span>Q{j+1}.</span> {question}</h4><div class="quiz-options" role="group" aria-labelledby="{qid}">'+''.join(f'<button type="button" data-answer-choice="{k}" aria-pressed="false">{o}</button>' for k,o in enumerate(options))+f'</div><p class="answer-status" role="status"></p><details class="answer-explanation"><summary>해설 펼치기</summary><p>{reason}</p><p><strong>정답:</strong> {options[answer]}</p></details></article>'
    return out+'</section>'

head=legacy['head'].replace('6개의 시각 실험','12장·14개의 시각 실험').replace('이온 생성에서 어닐링까지. 도즈, 에너지, 깊이 분포와 채널링을 직접 바꾸며 배우는 한국어 반도체 이온주입 공정 실험실.','원자에서 LV/HV 트랜지스터 공정과 측정까지. 12장, 14개 실험, 장별 복습으로 배우는 한국어 이온주입 교재.')
head=head.replace('</head>','  <link rel="stylesheet" href="./textbook.css">\n  <script defer src="./textbook.js"></script>\n  <script defer src="./devices.js"></script>\n</head>')
out=head+'''<body><a class="skip-link" href="#main">본문으로 건너뛰기</a><header class="topbar"><a href="#intro" class="brand" aria-label="IMP LAB 학습 지도"><span class="brand-mark" aria-hidden="true">i<span>+</span></span><strong>IMP<span class="brand-light"> LAB</span></strong></a><span class="top-caption">이온주입 인터랙티브 교재</span><div class="top-actions"><a href="#review">용어·복습</a><a href="#sources">자료와 모형</a><button id="menu-toggle" class="menu-toggle" type="button" aria-expanded="false" aria-controls="sidebar">목차</button></div></header><aside class="sidebar" id="sidebar" aria-label="학습 목차"><div class="side-eyebrow">PROCESS TEXTBOOK <span>IMP</span></div><p class="side-title">이온주입<span>원자에서 소자, 측정까지</span></p><a class="map-link" href="#intro">전체 학습 지도 ↗</a><nav id="chapter-nav" aria-label="장별 탐색">'''+''.join(navlink(c,i+1) for i,c in enumerate(CHAPTERS))+'''</nav><div class="side-note"><a href="#review">용어집 · 종합 복습</a><a href="#sources">출처 · 모형의 가정</a></div><div class="reading-progress"><span id="progress-label">학습 지도</span><div class="progress-track"><span id="progress-fill"></span></div></div></aside><main id="main" tabindex="-1"><div class="page-wrap"><div class="reader-tools"><p id="reader-location" role="status">원자 → 공정 → 소자 → 해석</p><button id="reader-all" type="button" aria-pressed="false">전체 이어 읽기</button></div><noscript><div class="noscript">JavaScript가 꺼져 있어 모든 장을 이어서 표시합니다. 본문과 해설은 읽을 수 있지만 실험 조작에는 JavaScript가 필요합니다.</div></noscript><section id="intro" data-reader aria-labelledby="page-title"><div class="intro"><div><p class="eyebrow">INTERACTIVE PROCESS TEXTBOOK / IMP</p><h1 id="page-title">원자를 심어,<br><em>전기의 길을 바꾸다.</em></h1><p class="intro-copy">전하 하나에서 시작해, 트랜지스터의 영역까지.<br>읽고, 예측하고, 직접 바꾸며 이온주입을 배웁니다.</p><div class="intro-meta"><span>12장 · 14개 실험</span><span>입문 → 학부 연결</span><a href="#atoms">1장부터 시작하기 →</a></div></div><div class="intro-stamp" aria-hidden="true"><span>ION<br>IMPLANTATION</span><strong>IMP</strong><div>CONTROL THE DOSE.<br>SHAPE THE PROFILE.</div><span class="stamp-corner">Si / 14</span></div></div><div class="model-banner"><span class="model-icon" aria-hidden="true">i</span><p><strong>개념을 위한 실험실입니다.</strong> 장비 설정·양산 레시피·소자 성능을 예측하지 않습니다. 물리식을 계산하는 실험과 임의 단위를 쓰는 개념 실험의 가정을 각 화면에 표시합니다. <a href="#models">가정과 한계</a></p></div><div class="reading-pair start-guide"><div><h2>앞에서 배운 말로<br>다음 질문을 풉니다.</h2><p>처음이면 1장부터 읽으세요. 공정을 알고 있다면 5장부터, 영역별 주입을 보고 싶다면 11장으로 이동한 뒤 선수 개념을 되짚어도 좋습니다.</p></div><div><h3>장마다 이렇게 공부합니다</h3><p>목표 확인 → 쉬운 설명 → 실험 전 예측 → 한 조건 바꾸기 → 그래프·식으로 해석 → 요약·해설 문항. 수식은 기호와 단위를 먼저 소개합니다.</p><a class="feature-link" href="#devices">LV/HV · NMOS/PMOS 공정 단면 실험 ↗</a></div></div><div class="roadmap" aria-label="12장 학습 지도">'''
for i,c in enumerate(CHAPTERS):
    out+=f'<a class="chapter-card" href="#{c["id"]}"><span>{i+1:02} / {c["level"]}</span><h2>{i+1}장. {c["title"]}</h2><p>{c["goals"][0]}</p><b aria-hidden="true">↗</b></a>'
out+='</div></section>'
for i,c in enumerate(CHAPTERS):
    id=c['id']; content=c['after']
    for key,value in LABS.items():content=content.replace('{{'+key+'}}',value)
    out+=f'''<section class="chapter" id="{id}" data-reader aria-labelledby="{id}-title"><div class="chapter-heading"><span class="chapter-number">{i+1:02}</span><div><p class="eyebrow">{c['english']}</p><h2 id="{id}-title">{i+1}장. {c['title']}</h2></div><span class="chapter-tag">{c['level']}</span></div><p class="prerequisite">앞 장과 연결 · {c['bridge']}</p><div class="chapter-goals"><h3>이 장을 읽고 나면</h3><ul>{li(c['goals'])}</ul></div><div class="chapter-jumps"><a href="#{id}-experiment">실험으로 이동 ↓</a><a href="#{id}-summary">핵심 정리 ↓</a><a href="#{id}-check">확인 문항 ↓</a><a href="#review">용어 찾아보기</a></div><p class="lead">{c['lead']}</p><div class="chapter-prose">{c['before']}</div><div id="{id}-experiment" class="experiment-anchor">{LABS.get(id,legacy.get(id,''))}</div><div class="chapter-prose">{content}</div><aside class="chapter-summary" id="{id}-summary"><h3>핵심 정리</h3><ul>{li(c['summary'])}</ul></aside>{quizzes(c)}{links(i)}</section>'''
out+='''<section id="review" class="supplement" data-reader aria-labelledby="review-title"><p class="eyebrow">RECALL AND RECONNECT</p><h2 id="review-title">용어집과 종합 복습</h2><p class="lead">용어는 해당 장으로 돌아가는 입구입니다. 검색 후 설명을 확인하고, 문항에서 헷갈린 조건은 실험으로 다시 검증해 보세요.</p><label for="glossary-search">용어 찾기 · 한국어 또는 영어</label><input type="search" id="glossary-search" placeholder="예: 채널, dose, 활성화"><p id="glossary-count" role="status">40개 용어</p><dl class="glossary">'''
for i,(term,desc,chapter) in enumerate(GLOSSARY):out+=f'<div data-term="{html.escape(term.lower())}" id="term-{i+1}"><dt>{term}</dt><dd>{desc} <a href="#{chapter}">해당 장에서 복습 ↗</a></dd></div>'
out+='</dl><h3 class="glossary-title">여러 장을 연결하는 네 질문</h3>'+legacy['review']+'<a class="feature-link" href="#atoms">1장부터 다시 읽기 →</a></section>'
source=legacy['sources'].replace('class="sources-section"','class="sources-section" data-reader')
newrefs=''.join(f'<li id="ref-{key}"><a href="{url}" target="_blank" rel="noopener noreferrer">{title}</a><span>{desc}</span></li>' for key,title,url,desc in REFERENCES)
source=source.replace('</ol>',newrefs+'</ol>',1)
source=source.replace('<div class="models"', '<p>기초와 소자 물리는 MIT 공개 강의 등으로 교차 확인했습니다. 원문 표기 오류나 과도한 일반화는 그대로 옮기지 않았습니다. 이 사이트의 모든 단면·질문·예제·코드는 별도로 작성했습니다.</p><div class="models"')
source=source.replace('<h3>실험에 사용한 가정</h3>','''<h3>실험에 사용한 가정</h3><details><summary>기초·소자·확산 실험의 추가 가정</summary><div><p>전하 실험은 q=(Z−Nₑ)e의 계수 모형이며 이온화 에너지·안정성을 계산하지 않습니다. 캐리어 실험은 하나의 전자·정공 쌍의 상태 변화를 표시합니다. 보상 실험은 농도를 nᵢ로 정규화하고 Δ=Nᴅ−Nᴀ, n=(Δ+√(Δ²+4))/2, p=1/n을 계산합니다. MOS 실험의 표면 상태 경계는 임의 척도이며 실제 전압이 아닙니다.</p><p>소자 실험은 단계별 영역 사각형과 정성 분포를 연결합니다. LV는 평면 웰·확장 구조, HV는 측면 드리프트 구조와 극성을 뒤집은 대응 예제입니다. 마스크는 완전 차단으로, 선택한 소자 밖은 보호된 것으로 가정합니다. 도펀트 영역은 활성화 뒤의 의도된 유형으로 표시하되 어닐링 전의 실제 전기적 농도를 주장하지 않습니다. 채널 길이를 만드는 이중 확산, 격리·할로·금속 배선·필드 플레이트·RESURF 설계·실제 마스크 투과를 계산하지 않습니다.</p><p>확산 실험은 μ=4, σ₀=0.8인 가우스와 반사 가우스를 x≥0에서 더해 면적 1을 유지합니다. σ²=σ₀²+2τ이며 그래프는 유한 구간, 총량 표시는 전체 반공간 기준입니다. 활성 비율 f와 이동도 비율 m은 균일한 가정값이며 상대 면저항은 0.5/(fm)입니다. 실제 온도·시간·깊이·농도·저항 단위로 환산하지 않습니다.</p></div></details>''')
source=re.sub(r'<p class="design-credit">.*?</p>', '''<div class="design-credit"><h3>직접 확인한 학습 경험 참고</h3><ul><li><a href="https://books.euiyun.com/">Books 교재 목록</a>: 반도체 분야의 관련 교재 탐색.</li><li><a href="https://sensorbook.euiyun.com/chapters/fabrication.html">SensorBook · 제조 공정과 패키징</a>: 에너지·도즈 조작과 프로파일, 공정 단면 스테퍼의 연결 → 7장과 11장에 적용.</li><li><a href="https://dopingbook.euiyun.com/chapters/flow.html">DopingBook · 공정 흐름 속의 도핑</a>: 단계별 단면·이전/다음·영역 목적 설명 → 네 소자 예제의 마스크·주입 창·분포 관찰로 확장.</li><li><a href="https://devicebook.euiyun.com/chapters/mosfet.html">DeviceBook · MOSFET</a>: 조작하는 소자 상태와 수식 해석의 연결 → 4장의 전압 부호·반전과 12장의 가정별 해석에 적용.</li></ul><p>상호작용과 설명의 연결 방식을 참고했습니다. 원문·그림·CSS·JavaScript 코드는 가져오지 않았습니다. 참고 교재와 본 교재 실험의 수치를 동일한 공정 데이터로 취급하지 않습니다.</p></div>''',source)
out+=source+'''<footer><a class="brand" href="#intro"><span class="brand-mark" aria-hidden="true">i<span>+</span></span><strong>IMP LAB</strong></a><p>원리와 결과를 연결하는 이온주입 교재<br><span>공개자료 확인 · 2026.10.07</span></p><a href="#intro">학습 지도</a></footer></div></main></body></html>'''
assert '{{' not in out
(ROOT/'site/index.html').write_text(out,encoding='utf-8',newline='\n')
print(f'Built {len(CHAPTERS)} chapters, {len(LABS)+6} labs, {sum(len(c["quiz"]) for c in CHAPTERS)+4} questions, {len(GLOSSARY)} glossary terms.')
